framework:
  swagger:
    title: 用户
    base-package: com.framework.cloud.user.api.controller
    group-name: user
  mybatis:
    mapperScanner: com.framework.cloud.user.infrastructure.mapper
    tenant:
      is-open: true
      ignore-table-names: 
        - t_permission
  redis:
    prefix: user
    host: 127.0.0.1
    password: 123456
  elasticsearch:
    uris: 127.0.0.1:9200,127.0.0.1:9201
    username: elastic
    password: elastic
seata:
  tx-service-group: user-group
  service:
    vgroup-mapping:
      user-group: seata-cluster
spring:
  shardingsphere:
    props:
      sql-show: true
    datasource:
      names: user
      user:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/framework-user?characterEncoding=utf8&useSSL=false&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: mysql
        password: mysql
    #分片规则 https://blog.csdn.net/qq_34279995/article/details/122421989
    rules:
      sharding:
        #默认key生成策略
        default-key-generate-strategy:
          column: id
          key-generator-name: snowflake
        tables:
          t_user:
            actualDataNodes: user.t_user_$->{0..1}
            tableStrategy:
              standard:
                #分片策略
                shardingColumn: id
                #分片策略名称
                shardingAlgorithmName: user_id
          t_user_auth:
            actualDataNodes: user.t_user_auth_$->{0..5}
            tableStrategy:
              standard:
                shardingColumn: user_id
                shardingAlgorithmName: user_auth_user_id
        #分片策略
        sharding-algorithms:
          user_id:
            #hash取模
            type: HASH_MOD
            props:
              #分片数量
              sharding-count: 2
          #策略名称
          user_auth_user_id:
            #采用哪种类型
            type: HASH_MOD
            props:
              sharding-count: 6
      encrypt:
        query-with-cipher-column: true
        encryptors:
          encryptor_md5:
            type: md5
            props:
              md5-key-value: 979
          encryptor_aes:
            type: aes
            props:
              aes-key-value: 979
        tables:
          t_user:
            columns:
              email:
                cipherColumn: email
                encryptorName: encryptor_aes
              username:
                cipherColumn: username
                encryptorName: encryptor_aes
              mobile:
                cipherColumn: mobile
                encryptorName: encryptor_aes
          t_user_auth:
            columns:
              identifier:
                cipherColumn: identifier
                encryptorName: encryptor_aes
              credential:
                cipherColumn: credential
                encryptorName: encryptor_md5