framework:
  swagger:
    title: 支付
    basePackage: com.framework.cloud.pay.api.controller
  mybatis:
    tenant:
      is-open: true
  redis:
    prefix: pay
    host: 127.0.0.1
    password: 123456
spring:
  shardingsphere:
    props:
      sql-show: true
    mode:
      type: Memory
    datasource:
      names: pay
      pay:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/framework-pay?characterEncoding=utf8&useSSL=false&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: dev
        password: 123456
    rules:
      sharding:
        #默认key生成策略
        default-key-generate-strategy:
          column: id
          key-generator-name: snowflake
        tables:
          t_pay_order:
            #定义表表名区间
            actualDataNodes: pay.t_pay_order_$->{2022..2023}_0$->{1..9},pay.t_pay_order_$->{2022..2023}_$->{10..12}
            #分片算法
            tableStrategy:
              standard:
                #分片键
                shardingColumn: create_time
                #分片策略
                shardingAlgorithmName: order_create_time
          t_pay_notify:
            actualDataNodes: pay.t_pay_notify_$->{0..9}
            #分片算法
            tableStrategy:
              standard:
                #分片键
                shardingColumn: pay_order_id
                #分片策略
                shardingAlgorithmName: notify_pay_order_id
        #分片策略
        sharding-algorithms:
          #策略名称
          order_create_time:
            #采用哪种类型
            type: CLASS_BASED
            props:
              #STANDARD、COMPLEX、HINT （org.apache.shardingsphere.sharding.algorithm.sharding.classbased.ClassBasedShardingAlgorithmStrategyType）
              strategy: STANDARD
              algorithmClassName: com.framework.cloud.pay.api.application.shading.OrderTimePreciseShardingAlgorithm
          #支付回调id分片名称
          notify_pay_order_id:
            #内嵌
            type: INLINE
            props:
              algorithm-expression: t_pay_notify_$->{pay_order_id % 10}