framework:
  swagger:
    title: 平台
    base-package: com.framework.cloud.platform.api.controller
    group-name: platform
  mybatis:
    mapperScanner: com.framework.cloud.platform.infrastructure.mapper
    tenant:
      is-open: true
      ignore-table-names: 
        - t_tenant
        - t_gateway_route
        - t_pay_channel
        - t_pay_mode
  redis:
    prefix: platform
    host: 127.0.0.1
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: dev
    password: 123456
    virtual-host: /
spring:
  shardingsphere:
    props:
      sql-show: true
    mode:
      type: Memory
    datasource:
      names: platform
      platform:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/framework-platform?characterEncoding=utf8&useSSL=false&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: dev
        password: 123456
    rules:
      sharding:
        #不分库分表 none
        default-table-strategy:
          none: none
        default-key-generate-strategy:
          column: id
          key-generator-name: snowflake
      encrypt:
        query-with-cipher-column: true
        encryptors:
          encryptor_md5:
            type: md5
            props:
              md5-key-value: 979
        tables:
          t_tenant:
            columns:
              secret:
                cipherColumn: secret
                encryptorName: encryptor_md5
  cloud:
    stream:
      bindings:
        gateway-route-channel:
          destination: gateway-route
          content-type: application/json
          group: ${spring.application.name}
          consumer:
            concurrency: 4
        gateway-route-delete-channel:
          destination: gateway-route-delete
          content-type: application/json
          group: ${spring.application.name}
          consumer:
            max-attempts: 1
            concurrency: 4
      binders:
        rabbit:
          type: rabbit