server:
  max-http-header-size: 102400
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
#端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  security:
    health:
      elasticsearch:
        enabled: false

#日志
logging:
  config: classpath:logback-spring.xml
