#增强模式
knife4j:
  enable: ${framework.knife4j.enabled:true}
  basic:
    enable: ${framework.knife4j.basic.enabled:false}
    username: ${framework.knife4j.basic.username:979}
    password: ${framework.knife4j.basic.password:wusiwei979}
#文档
framework:
    swagger3:
        #是否开启
        enabled: ${framework.swagger.enabled:true}
        #扫描路径
        base-package: ${framework.swagger.base-package}
        #页面标题
        title: ${framework.swagger.title}
        #描述
        description: ${framework.swagger.description:文档}
        #版本号
        version: ${framework.swagger.version:v3}
        #许可
        license: ${framework.swagger.license:暂无}
        #许可链接
        license-url: ${framework.swagger.license-url:暂无}
        #分组
        group-name: ${framework.swagger.group-name}
        #作者信息
        contact:
            #名称
            name: ${framework.swagger.contact.name:979}
            #链接
            url: ${framework.swagger.contact.url:无}
            #邮箱
            email: ${framework.swagger.contact.email:18683789594@163.com}
        #认证
        authorization:
            name: ${framework.swagger.authorization.name:Authorization}
            auth-regex: ${framework.swagger.authorization.auth-regex:^.*$}
